[project]
name = "Transam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.42.0",
    "langchain-community>=0.3.27",
    "rank-bm25>=0.2.2",
    "smolagents[all,litellmmodel]>=1.21.1",
]
